name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Prepare the Pull Request Payload artifact. If this fails, we
    # we fail silently using the `continue-on-error` option. It's
    # nice if this succeeds, but if it fails for any reason, it
    # does not mean that our lint-test checks failed.
    - name: Prepare Pull Request Payload artifact
      id: prepare-artifact
      if: always() && github.event_name == 'pull_request'
      continue-on-error: true
      run: cat $GITHUB_EVENT_PATH | jq '.pull_request' > pull_request_payload.json

    # This only makes sense if the previous step succeeded. To
    # get the original outcome of the previous step before the
    # `continue-on-error` conclusion is applied, we use the
    # `.outcome` value. This step also fails silently.
    - name: Upload a Build Artifact
      if: always() && steps.prepare-artifact.outcome == 'success'
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-payload
        path: pull_request_payload.json
